"use client";

import Link from "next/link";
import { useEffect, useId, useRef, useState } from "react";
import { defaultProfile, needsReconfirmation, projectTasks, roleSites, ROLE_LABELS, stageName, type Role, type Site, type View } from "./model";
import { useLab } from "./store";
import { DemoLearning } from "./DemoLearning";
import { Button, Icon, Pill } from "./ui";
import s from "./Lab.module.css";
import g from "./Guidance.module.css";

export function WelcomeView({ onRole }: { onRole: (role: Role, view: View) => void; onEdit: (id: string) => void }) {
  const { state } = useLab();
  const profile = state.profile ?? defaultProfile();
  return <div className={g.welcome}>
    <Pill tone="accent"><Icon name="sun" size={14} />Find your place in the journey</Pill>
    <h1>Shared sunlight.<br /><em>Clear next steps.</em></h1>
    <p className={g.intro}>Learn at your pace, then explore a fictional project. This introduction is optional and always available.</p>
    <div className={g.paths}>
      {[
        { icon: "roof", title: "Offer a place", body: "Describe your goals before adding a rooftop or parcel.", action: "Review my profile", run: () => onRole("site-owner", "profile") },
        { icon: "pipeline", title: "Move a project forward", body: "Review evidence, record a decision and keep the handoffs clear.", action: "Explore operator work", run: () => onRole("operator", "queue") },
        { icon: "heart", title: "Explore an opportunity", body: "Set a mandate and express interest without committing funds.", action: "Explore investor work", run: () => onRole("investor", "mandate") },
      ].map((path, index) => <button type="button" key={path.title} className={g.path} onClick={path.run}>
        <span className={g.pathNumber}>0{index + 1}</span><span className={g.pathIcon}><Icon name={path.icon} size={32} /></span><h2>{path.title}</h2><p>{path.body}</p><span className={g.pathAction}>{path.action}<Icon name="arrow" size={16} /></span>
      </button>)}
    </div>
    <div className={g.welcomeActions}><Button variant="primary" onClick={() => onRole("site-owner", profile.completed ? "sites" : "profile")}>{profile.completed ? "Return to my sites" : "Start with my profile"}</Button><Link href="/join" className={s.button}>Original participation flow</Link></div>
    <DemoLearning />
    <p className={g.boundary}><Icon name="lock" size={16} />Fictional preview. No real account, legal agreement, utility connection, microphone capture or payment.</p>
  </div>;
}

export function scriptedReply(text: string, role: Role, site?: Site): string {
  const value = text.toLowerCase();
  const context = site ? `For ${site.name}: ` : "In this preview: ";
  if (/\badoption\b|\bhuman (?:help|support)\b|\bonboarding help\b|\bproject manager\b|\bcontact\b|\breach (?:a person|someone)\b/.test(value)) return "Human adoption support means a person helping a participant understand the process, agree next steps and resolve access or project questions. This panel is only scripted help. No verified support contact is configured here; no project-manager outreach or message is sent. Use an already established project-team channel outside this preview.";
  if (/\b(next|task|needed|request)\b/.test(value)) {
    if (!site) return "Select a project in the workspace header to get its next steps. The Action Center and Documents view use the same project requests.";
    const tasks = projectTasks(site).filter((task) => task.status !== "reviewed" && (role === "operator" || task.kind === "evidence"));
    return context + (role === "investor" ? "Review the published summary and your mandate. Interest is non-binding; permitted diligence is separate from any commitment." :
      `${site.nextAction}. ${tasks.length ? `Open tasks: ${tasks.map((task) => task.title).join("; ")}.` : "No outstanding example tasks are recorded."} Opening a file does not mark it reviewed.`);
  }
  if (/upload|document|file|bill|sign|draft|report|export/.test(value)) return context + "Documents stores metadata, not file bytes. Drafts & reports provides editable, source-prefilled demo briefings and separate assessment reports; HTML/CSV exports are actual local files. They are not approved legal templates, signatures or recipient delivery.";
  if (/return|roi|cost|saving|price|money|payback|carbon|impact/.test(value)) return "The comparison uses ten fixed source fixtures. Owner benefit, project payback, investor return and utility savings are different measures. Unavailable project-specific calculations stay uncalculated; no funds or verified impact are generated by this preview.";
  if (/invest|fund|capital|mandate|deal|interest/.test(value)) return "A completed fictional mandate allows non-binding interest in a published project. A separate minimal notice reaches the owner view, without investor identity or amount. Withdrawal revokes preview diligence access but preserves truthful history. Publication is not funding.";
  if (/assessment|screen|rerun|original|decision|approve|accept/.test(value)) return context +
    "Original assessment, latest illustrative result and human decision are separate. Reruns are deliberate selected-fixture examples, not a provider call. A failed example retains the last result." +
    (site && needsReconfirmation(site) ? " This project's changed evidence or assessment needs human reconfirmation." : " New evidence never silently replaces a human decision.");
  if (/operator|stage|review|reject|pipeline/.test(value)) return context +
    `${site ? `Recorded stage: ${stageName(site.stage)}. ` : ""}Human acceptance, starting pre-development, advancing a stage and publishing are distinct actions. Example task blockers explain what still needs review; they are not an approved universal solar policy. Typed notes do not execute any of those actions.`;
  if (/roof|land|site|address|submit|profile/.test(value)) return "Start with the revisitable fictional profile, then add a site. Save and return to the same intake. Conditional evidence and consent are explained before submission. Addresses and roof geometry are not verified, and no real identity is created.";
  if (/voice|audio|microphone|live|grid|battery|dispatch|utility|inverter|model/.test(value)) return "This is a solar-origination preview, not live device control. No microphone, browser speech, utility retrieval, AI model or paid provider is connected. Typed guidance remains available. The Service status panel names the unavailable capabilities.";
  if (/\b(hello|hi|hey)\b/.test(value)) return `Hello. This is scripted ${ROLE_LABELS[role].toLowerCase()} guidance${site ? ` for ${site.name}` : ""}. I can explain the current task, documents, assessment or next handoff. I cannot perform actions for you.`;
  return context + "I can explain the next task, documents and drafts, preliminary assessment, project stages or non-binding interest. These answers come from local workflow rules, not an AI model or private source search. Use the visible controls to make a change.";
}

export function GuidanceAssistant({ onClose, onNavigate, role = "site-owner", siteId }: {
  onClose?: () => void; onNavigate?: (role: Role, view: View) => void; role?: Role; siteId?: string;
}) {
  const headingId = useId();
  const { state, notify } = useLab();
  const site = roleSites(state, role).find((item) => item.id === siteId);
  const [messages, setMessages] = useState([{ author: "assistant", text: "What would help you take the next step? I explain this preview; I do not execute actions." }]);
  const [input, setInput] = useState("");
  const inputRef = useRef<HTMLTextAreaElement>(null);
  const focusOnMount = useRef(Boolean(onClose));
  const end = useRef<HTMLDivElement>(null);
  useEffect(() => {
    if (focusOnMount.current) inputRef.current?.focus();
  }, []);
  useEffect(() => {
    const log = end.current?.parentElement;
    if (log) log.scrollTop = log.scrollHeight;
  }, [messages]);
  const send = (question: string) => {
    if (!question.trim()) { notify("Type a question about the current project or workflow."); return; }
    setMessages((current) => [...current, { author: "user", text: question.trim() }, { author: "assistant", text: scriptedReply(question, role, site) }]);
    setInput("");
  };
  return <aside id="workspace-guidance" className={g.companion} aria-labelledby={headingId}>
    <div className={g.companionHeading}><div><p className={s.eyebrow}>Contextual help</p><h2 id={headingId}>Ask SunSum</h2></div>{onClose && <Button variant="ghost" aria-label="Close guidance" onClick={onClose}><Icon name="close" /></Button>}</div>
    <div className={g.assistant}><Pill tone="warning">Scripted guidance &middot; no AI model</Pill>
      <p className={g.scope}>{ROLE_LABELS[role]} &middot; {site?.name ?? "Workspace overview"}<br />Source: local synthetic workflow and visible project state.</p>
      <div className={g.quickPaths}>
        <button onClick={() => send("What is the next task?")} type="button"><Icon name="inbox" size={16} />Explain next steps</button>
        {onNavigate && <button onClick={() => onNavigate(role, "documents")} type="button"><Icon name="file" size={16} />Open documents</button>}
        {onNavigate && <button onClick={() => onNavigate(role, "reports")} type="button"><Icon name="download" size={16} />Open reports</button>}
        <button onClick={() => send("What is live or unavailable?")} type="button"><Icon name="help" size={16} />Explain limits</button>
      </div>
      <div className={g.messages} role="log" aria-label="Guidance conversation" aria-live="polite">{messages.map((message, index) => <div key={index} className={message.author === "user" ? g.userMessage : g.assistantMessage}>{message.author === "assistant" && <span className={g.messageAvatar}><Icon name="sun" size={16} /></span>}<p>{message.text}</p></div>)}<div ref={end} /></div>
      <form className={g.composer} onSubmit={(event) => { event.preventDefault(); send(input); }}>
        <textarea ref={inputRef} aria-label="Ask a question" placeholder="Ask about the next handoff..." value={input} onChange={(event) => setInput(event.target.value)} rows={3} />
        <div className={g.composerActions}><span className={g.typedOnly}>Typed questions only</span><Button variant="primary" type="submit" aria-label="Send question" disabled={!input.trim()}><Icon name="arrow" size={17} /></Button></div>
      </form><p className={g.assistantDisclaimer}>No microphone capture, attachments, hidden actions or conversation storage. Change role/project to start a fresh guidance context.</p>
      <details className={g.support}><summary>Human support is different</summary><p>Adoption support is a person helping with the process and next handoff. This panel cannot contact a project manager. No verified support contact is configured; use an already established project-team channel.</p></details>
    </div>
  </aside>;
}
