using './resources.bicep'

param environmentName = 'dev-test'
param location = 'centralus'
param appServicePlanName = 'asp-sunsum-dev-test-centralus'
param webAppName = 'app-sunsum-dev-test-centralus'
param storageAccountName = 'stsunsumdevtestcentralus'
param postgresServerName = 'db-sunsum-dev-test-centralus'
param databaseName = 'sunsum_test'
param runtimeRoleName = 'sunsum_runtime'
param tenantId = '00000000-0000-0000-0000-000000000000'
param postgresAdminObjectId = '00000000-0000-0000-0000-000000000000'
param postgresAdminPrincipalName = '<postgres-admin-principal-name>'
param postgresAdminPrincipalType = 'User'
param postgresTier = 'Burstable'
param postgresSkuName = 'Standard_B1ms'
param postgresStorageSizeGB = 32
param postgresVersion = '17'
